In [2]:
import numpy as np

In [16]:
a=np.array([1.0,2.0,3.0,4.0,5.0])
print("Original array: ",a)
b=a+2
print("Addition by 2: ",b)
c=a*3
print("Multiplication by 3: ",c)
d=a/2
print("Division by 2: ",d)


Original array:  [1. 2. 3. 4. 5.]
Addition by 2:  [3. 4. 5. 6. 7.]
Multiplication by 3:  [ 3.  6.  9. 12. 15.]
Division by 2:  [0.5 1.  1.5 2.  2.5]


In [ ]:
#Q1
arr=np.array([1,2,3,6,4,5])
a2=np.flip(arr)
a2

array([5, 4, 6, 3, 2, 1])

In [ ]:
#Q2
x = np.array([1,2,3,4,5,1,2,1,1,1]) 

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

In [ ]:
#Q3
arr2=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr2[0][1])
print(arr2[2][0])

20
70


In [26]:
Vandit= np.linspace(10, 100, 25)
print(Vandit)
print("Dimensions:", Vandit.ndim)
print("Shape:", Vandit.shape)
print("Total elements:", Vandit.size)
print("Data type:", Vandit.dtype)
print("Total bytes:", Vandit.nbytes)
trans=Vandit.reshape(25,1)
print(trans)
print(Vandit.T)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [27]:
ucs420_Vandit = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_Vandit)

print("Mean:", np.mean(ucs420_Vandit))
print("Median:", np.median(ucs420_Vandit))
print("Maximum:", np.max(ucs420_Vandit))
print("Minimum:", np.min(ucs420_Vandit))
print("Unique elements:", np.unique(ucs420_Vandit))

reshaped_ucs420_Vandit = ucs420_Vandit.reshape(4, 3)
print("Reshaped Array (4 x 3):")
print(reshaped_ucs420_Vandit)

resized_ucs420_Vandit = np.resize(ucs420_Vandit, (2, 3))
print("Resized Array (2 x 3):")
print(resized_ucs420_Vandit)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
